### ISSUE TITLE
48k/24bit WAV File Processed by MpegFormatConversionProvider

### ISSUE THREAD

**Issue by Cahlien** [umjammer/mp3spi#16]
## Cause

When playing a 48k/24bit WAV file, the wrong decoder is used if and only if the `javazoom.spi.mpeg.sampled.convert.MpegFormatConversionProvider` is included in the `META-INF/services/javax.sound.sampled.spi.FormatConversionProvider` file.  Otherwise the WAV file plays fine whether it's 44.1k/16bit or 48k/24bit.  

## Error Description

An `ArrayIndexOutOfBoundsException` occurs when the MpegFormatConversionProvider attempts to process the 48k/24bit WAV file, illustrating that a decoder other than the WAV decoders was used:

```plaintext
java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 15
        at javazoom.jl.decoder.LayerIDecoder$SubbandLayer1Stereo.readAllocation(LayerIDecoder.java:361)
        at javazoom.jl.decoder.LayerIDecoder.readAllocation(LayerIDecoder.java:98)
        at javazoom.jl.decoder.LayerIDecoder.decodeFrame(LayerIDecoder.java:69)
        at javazoom.jl.decoder.Decoder.decodeFrame(Decoder.java:131)
        at javazoom.spi.mpeg.sampled.convert.DecodedMpegAudioInputStream.execute(DecodedMpegAudioInputStream.java:193)
        at org.tritonus.share.TCircularBuffer.read(TCircularBuffer.java:101)
        at org.tritonus.share.sampled.convert.TAsynchronousFilteredAudioInputStream.read(TAsynchronousFilteredAudioInputStream.java:157)
        at org.tritonus.share.sampled.convert.TAsynchronousFilteredAudioInputStream.read(TAsynchronousFilteredAudioInputStream.java:143)

**Comment by umjammer** [comment]
can you send me the wav?
if it's copyrighted, cut out the first few seconds of it.

---

on my env. it's no problem to play 48k 24bit wav

```shell
$ pwd
~/src/java/mp3spi
$ mkdir tmp
$ cd tmp
$ ffmpeg -i ../src/test/resources/test.wav -ar 48000 -acodec pcm_s24le pcm-48k_24.wav
```

add following to `src/test/java/Test3.java`
```java

    @Test
    void testIssue16() throws Exception {
        String file = "tmp/pcm-48k_24.wav";
Debug.println(file);
        InputStream is = new BufferedInputStream(Files.newInputStream(Paths.get(file)));
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(is);
        play(audioInputStream);
    }
```

output

```shell
$ pwd
~/src/java/mp3spi
$ mvn verify -Dtest=Test3#testIsuue16

 ︙

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running Test3
2024-08-12 05:06:29,091 [INFO] time: 3000
	at Test3.setup(Test3.java:83)
2024-08-12 05:06:29,092 [INFO] tmp/pcm-48k_24.wav
	at Test3.testIsuue16(Test3.java:210)
2024-08-12 05:06:29,186 [INFO] PCM_SIGNED 48000.0 Hz, 24 bit, stereo, 6 bytes/frame, little-endian
	at Test3.play(Test3.java:96)
2024-08-12 05:06:29,186 [INFO] PCM_SIGNED 48000.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian
	at Test3.play(Test3.java:103)
2024-08-12 05:06:29,271 [INFO] play
	at Test3.lambda$play$0(Test3.java:110)
2024-08-12 05:06:32,378 [INFO] done
	at Test3.lambda$play$0(Test3.java:113)
```

**Comment by Cahlien** [comment]
I think you hit the nail on the head, brother.  I cut the first portion off with Audacity and it plays great.  Thank you, both for the response and just for maintaining this.

**Comment by alvdavi** [comment]
I found myself with the same issue today. I was checking, and it seems this is happening because the wave file has a JUNK chunk at the beginning. The current implementation https://github.com/umjammer/mp3spi/blob/master/src/main/java/javazoom/spi/mpeg/sampled/file/MpegAudioFileReader.java#L193 assumes the first chunk is the format chunk, and reads byte 20 (0x14) directly, which is still part of the JUNK chunk. This leads to the file eventually being considered a wav file.

Here are the headers for the file that was giving me issue:

![image](https://github.com/user-attachments/assets/9f89ede6-1f26-4f23-b47a-c47b4d5199d2)

Instead of byte 0x14, it should have skipped the JUNK chunk and read 0x50. For reference, the wav is a Rodecaster II recording. It seems all the recordings generated by the device include this JUNK chunk

EDIT: Also worth mentioning, even if misidentified, it is still possible for the wav file to play, but depending on the file, an exception like @Cahlien reported (with different length) can appear.

**Comment by umjammer** [comment]
thanks @alvdavi see 646d4d5

**Comment by alvdavi** [comment]
Thanks, my wav files with JUNK chunks are now skipped by the MpegAudioFileReader. I wonder if it would be possible for a wav file to contain a JUNK chunk at the beginning and then a fmt chunk that defines it as mp3 encoded. I've never seen one of those.

**Comment by umjammer** [comment]
riff wave format should be flexible, so it seems ok to contain junk chunk for every format type.
maybe expecting fmt chunk after magic is not good implementation.

but

imo
- mp3 reader spi should not read wav file
- wav reader spi should read wav file and return pcm or mp3 audio input stream seeing `fmt` chunk

i think it's not `MpegAudioFileReader`'s responsibility to read wav file. so i implemented it sloppily.
